[package]
name = "nu_plugin_cloud"
authors = ["Jack Wright"]
description = "A nushell plugin for working with cloud storage services"
repository = "https://github.com/ayax79/nu_plugin_cloud"
version = "0.2.11+0.116.0"
license = "MIT"
edition = "2024"

[dependencies]
async-lock = "3.4.2"
aws-config = { version = "1.12", features = ["sso"] }
aws-credential-types = "1.3"
bytes = "1.12"
env_logger = "0.11"
futures = "0.3"
itertools = "0.15"
log = "0.4"
mimalloc = "0.1.52"
mime_guess = "2.0.5"
nu-command = { version = "0.116.0", features = ["plugin"] }
nu-plugin = "0.116.0"
nu-plugin-engine = { version = "0.116.0", features = ["local-socket"] }
nu-protocol = { version = "0.116.0", features = ["plugin"] }
object_store = { version = "0.14", features = ["aws"] }
tokio = { version = "1.53", features = ["full"] }
url = "2.5"

[dev-dependencies]
nu-plugin-test-support = "0.116.0"
nu-command = "0.116.0"
